version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install 
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo first test codes
      - echo compiling the codes
      - npm run build
      - echo build finished, now moving to S3
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync build/ s3://demo-static-s3site --acl public-read
